# Generated by Django 5.2.12 on 2026-04-05 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companymembership_can_manage_projects_and_more'),
        ('customers', '0005_remove_customer_unique_customer_number_per_company_and_more'),
        ('projects', '0002_alter_project_created_by_alter_project_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='site_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_types', to='companies.company')),
            ],
            options={
                'db_table': 'projects_project_type',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projecttype'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'project_type'], name='projects_pr_company_dca84c_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttype',
            index=models.Index(fields=['company', 'is_active'], name='projects_pr_company_0a027e_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttype',
            index=models.Index(fields=['company', 'name'], name='projects_pr_company_d78336_idx'),
        ),
        migrations.AddConstraint(
            model_name='projecttype',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_project_type_name_per_company'),
        ),
    ]
