# Generated by Django 5.2.12 on 2026-04-06 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companymembership_can_manage_projects_and_more'),
        ('customers', '0005_remove_customer_unique_customer_number_per_company_and_more'),
        ('projects', '0003_project_site_location_projecttype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'is_active'], name='projects_pr_company_a834fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('project_number', ''), _negated=True), fields=('company', 'project_number'), name='uniq_project_number_per_company'),
        ),
    ]
