# Generated by Django 5.2.12 on 2026-03-13 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlanPublicIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WorkPlan Public ID Sequence',
                'verbose_name_plural': 'WorkPlan Public ID Sequences',
                'db_table': 'workplans_public_id_sequence',
            },
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, max_length=32, unique=True)),
                ('calendar_week', models.PositiveSmallIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plans', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_plans', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_work_plans', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_work_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Plan',
                'verbose_name_plural': 'Work Plans',
                'db_table': 'workplans_work_plan',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, max_length=32, unique=True)),
                ('work_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('planned_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('task_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plan_items', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_plan_items', to=settings.AUTH_USER_MODEL)),
                ('employee_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plan_items', to='companies.companymembership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plan_items', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_work_plan_items', to=settings.AUTH_USER_MODEL)),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workplans.workplan')),
            ],
            options={
                'verbose_name': 'Work Plan Item',
                'verbose_name_plural': 'Work Plan Items',
                'db_table': 'workplans_work_plan_item',
                'ordering': ['work_date', 'start_time', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workplan',
            index=models.Index(fields=['public_id'], name='workplans_w_public__e32ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='workplan',
            index=models.Index(fields=['company', 'calendar_week'], name='workplans_w_company_be11f2_idx'),
        ),
        migrations.AddIndex(
            model_name='workplan',
            index=models.Index(fields=['company', 'period_start', 'period_end'], name='workplans_w_company_97c194_idx'),
        ),
        migrations.AddIndex(
            model_name='workplan',
            index=models.Index(fields=['company', 'status'], name='workplans_w_company_b9dca8_idx'),
        ),
        migrations.AddConstraint(
            model_name='workplan',
            constraint=models.UniqueConstraint(fields=('company', 'calendar_week', 'period_start', 'period_end'), name='unique_workplan_per_company_period'),
        ),
        migrations.AddIndex(
            model_name='workplanitem',
            index=models.Index(fields=['public_id'], name='workplans_w_public__7bf201_idx'),
        ),
        migrations.AddIndex(
            model_name='workplanitem',
            index=models.Index(fields=['company', 'work_date'], name='workplans_w_company_2a5c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='workplanitem',
            index=models.Index(fields=['company', 'status'], name='workplans_w_company_96f251_idx'),
        ),
        migrations.AddIndex(
            model_name='workplanitem',
            index=models.Index(fields=['project'], name='workplans_w_project_d22649_idx'),
        ),
        migrations.AddIndex(
            model_name='workplanitem',
            index=models.Index(fields=['employee_membership'], name='workplans_w_employe_6aa3ee_idx'),
        ),
        migrations.AddIndex(
            model_name='workplanitem',
            index=models.Index(fields=['work_plan', 'work_date'], name='workplans_w_work_pl_c11eb8_idx'),
        ),
    ]
