# Generated by Django 5.2.12 on 2026-03-14 12:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companymembership_can_manage_projects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationPublicIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_public_id_sequence', to='companies.company')),
            ],
            options={
                'verbose_name': 'Vacation Public ID Sequence',
                'verbose_name_plural': 'Vacation Public ID Sequences',
            },
        ),
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('special', 'Special Leave'), ('unpaid', 'Unpaid Leave')], default='annual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_half_day_start', models.BooleanField(default=False)),
                ('is_half_day_end', models.BooleanField(default=False)),
                ('requested_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Automatically calculated working days (Mon-Fri) without public holidays.', max_digits=6)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('employee_note', models.TextField(blank=True)),
                ('manager_note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_vacation_requests', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to='companies.company')),
                ('employee_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacation_requests', to='companies.companymembership')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vacation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacation Request',
                'verbose_name_plural': 'Vacation Requests',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['company', 'status'], name='vacations_v_company_75db63_idx'), models.Index(fields=['company', 'employee_membership'], name='vacations_v_company_6e2ff6_idx'), models.Index(fields=['company', 'start_date', 'end_date'], name='vacations_v_company_b94f00_idx'), models.Index(fields=['company', 'is_active'], name='vacations_v_company_d33f2a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='vacation_end_date_gte_start_date')],
            },
        ),
    ]
