# Generated by Django 5.2.12 on 2026-03-14 13:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companymembership_can_manage_projects_and_more'),
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('entitled_days', models.DecimalField(blank=True, decimal_places=2, help_text='If empty, defaults to membership.vacation_days_per_year.', max_digits=6, null=True)),
                ('carried_over_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transferred vacation days from previous year.', max_digits=6)),
                ('manual_adjustment_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Manual plus/minus adjustment by HR or admin.', max_digits=6)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_balances', to='companies.company')),
                ('employee_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_balances', to='companies.companymembership')),
            ],
            options={
                'verbose_name': 'Vacation Balance',
                'verbose_name_plural': 'Vacation Balances',
                'ordering': ('-year', '-created_at'),
                'indexes': [models.Index(fields=['company', 'year'], name='vacations_v_company_18c0c7_idx'), models.Index(fields=['employee_membership', 'year'], name='vacations_v_employe_d610cf_idx'), models.Index(fields=['company', 'employee_membership', 'year'], name='vacations_v_company_f5ffd1_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'employee_membership', 'year'), name='unique_vacation_balance_per_employee_company_year')],
            },
        ),
    ]
