# Generated by Django 5.2.12 on 2026-03-14 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companymembership_can_manage_projects_and_more'),
        ('vacations', '0003_remove_vacationpublicidsequence_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationpublicidsequence',
            name='employee_membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_public_id_sequence', to='companies.companymembership'),
        ),
    ]
