# Generated by Django 5.2.12 on 2026-03-10 16:04

import apps.accounts.models
import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-Mail')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Nachname')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('diverse', 'Diverse'), ('not_specified', 'Not specified')], default='not_specified', max_length=20, verbose_name='Geschlecht')),
                ('phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Bitte eine gültige Telefonnummer eingeben.', regex='^[0-9+\\-\\s()/]{6,30}$')], verbose_name='Telefon')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.user_profile_upload_path, verbose_name='Profilbild')),
                ('document', models.FileField(blank=True, null=True, upload_to=apps.accounts.models.user_document_upload_path, verbose_name='Dokument')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Straße')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Stadt')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Land')),
                ('emergency_contact_person', models.CharField(blank=True, max_length=255, verbose_name='Notfallkontakt Person')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Bitte eine gültige Telefonnummer eingeben.', regex='^[0-9+\\-\\s()/]{6,30}$')], verbose_name='Notfallkontakt Telefon')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff-Status')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='E-Mail verifiziert')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='E-Mail verifiziert am')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Letzter Login am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Benutzer',
                'db_table': 'accounts_user',
                'ordering': ['-created_at'],
            },
        ),
    ]
