# Generated by Django 5.2.12 on 2026-03-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_publicidsequence_user_public_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicidsequence',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Öffentliche ID'),
        ),
    ]
