# Generated by Django 5.2.12 on 2026-03-10 16:57

import apps.companies.models
import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPublicIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Public ID Sequence',
                'verbose_name_plural': 'Company Public ID Sequences',
                'db_table': 'companies_public_id_sequence',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Firmen-ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Firmenname')),
                ('legal_form', models.CharField(choices=[('sole_proprietorship', 'Einzelunternehmen'), ('gbr', 'GbR'), ('ug', 'UG'), ('gmbh', 'GmbH'), ('ag', 'AG'), ('other', 'Sonstige')], default='other', max_length=50, verbose_name='Rechtsform')),
                ('industry', models.CharField(blank=True, max_length=120, verbose_name='Branche')),
                ('employee_range', models.CharField(blank=True, choices=[('1-5', '1-5'), ('6-20', '6-20'), ('21-50', '21-50'), ('50+', '50+')], max_length=10, verbose_name='Mitarbeiteranzahl')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Firmen-E-Mail')),
                ('phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Bitte eine gültige Telefonnummer eingeben.', regex='^[0-9+\\-\\s()/]{6,30}$')], verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Webseite')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Land')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Straße')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Stadt')),
                ('vat_id', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Bitte eine gültige USt-IdNr. eingeben, z. B. DE123456789.', regex='^[A-Z]{2}[A-Z0-9]{2,20}$')], verbose_name='USt-IdNr.')),
                ('tax_number', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Bitte eine gültige Steuernummer eingeben.', regex='^[0-9A-Za-z/\\-]{6,30}$')], verbose_name='Steuernummer')),
                ('commercial_register', models.CharField(blank=True, max_length=120, verbose_name='Handelsregister')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.companies.models.company_logo_upload_path, verbose_name='Logo')),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], default='free', max_length=20, verbose_name='Paketplan')),
                ('subscription_status', models.CharField(choices=[('active', 'Aktiv'), ('trial', 'Testphase'), ('expired', 'Abgelaufen'), ('canceled', 'Gekündigt'), ('suspended', 'Gesperrt')], default='trial', max_length=20, verbose_name='Abo-Status')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Testphase endet am')),
                ('billing_email', models.EmailField(blank=True, max_length=255, verbose_name='Abrechnungs-E-Mail')),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=100, verbose_name='Zeitzone')),
                ('language', models.CharField(default='de', max_length=10, verbose_name='Sprache')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Firmenbesitzer')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmen',
                'db_table': 'companies_company',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=20, verbose_name='Rolle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Beigetreten am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company', verbose_name='Firma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Firmenmitgliedschaft',
                'verbose_name_plural': 'Firmenmitgliedschaften',
                'db_table': 'companies_companymembership',
                'ordering': ['company__company_name', 'role', 'user__first_name', 'user__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['public_id'], name='companies_c_public__dd78c4_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_name'], name='companies_c_company_14f39a_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['subscription_plan'], name='companies_c_subscri_e613aa_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['subscription_status'], name='companies_c_subscri_4d5d82_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='companies_c_is_acti_03043b_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='companies_c_created_301a54_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['company', 'role'], name='companies_c_company_2aaa04_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['user'], name='companies_c_user_id_ae9f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['is_active'], name='companies_c_is_acti_4dc633_idx'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='unique_company_user_membership'),
        ),
    ]
