# Generated by Django 5.2.12 on 2026-03-14 10:20

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companymembership',
            name='can_manage_projects',
            field=models.BooleanField(default=False, verbose_name='Darf Projekte verwalten'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='contract_type',
            field=models.CharField(choices=[('full_time', 'Vollzeit'), ('part_time', 'Teilzeit'), ('mini_job', 'Minijob'), ('temporary', 'Befristet'), ('apprentice', 'Azubi'), ('intern', 'Praktikant'), ('freelancer', 'Freelancer'), ('other', 'Sonstiges')], default='full_time', max_length=30, verbose_name='Vertragstyp'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='department',
            field=models.CharField(blank=True, max_length=120, verbose_name='Abteilung'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Personalnummer'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Inaktiv'), ('on_leave', 'Beurlaubt'), ('terminated', 'Beendet')], default='active', max_length=20, verbose_name='Beschäftigungsstatus'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Eintrittsdatum'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Austrittsdatum'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='hourly_wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Lohn €/Std.'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='is_time_tracking_enabled',
            field=models.BooleanField(default=True, verbose_name='Zeiterfassung aktiviert'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='job_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='monthly_target_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('173.33'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Soll-Stunden / Monat'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Interne Notizen'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='vacation_days_per_year',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(366)], verbose_name='Urlaubstage / Jahr'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='weekly_target_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Soll-Stunden / Woche'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['company', 'employment_status'], name='companies_c_company_2168ab_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['employee_number'], name='companies_c_employe_3ed3bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_number', ''), _negated=True), fields=('company', 'employee_number'), name='unique_company_employee_number'),
        ),
    ]
