# Generated by Django 5.2.12 on 2026-04-04 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companymembership_can_manage_projects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gps_capture_mode',
            field=models.CharField(choices=[('off', 'Aus'), ('optional', 'Optional'), ('required', 'Pflicht')], default='off', help_text='Steuert, ob GPS beim Arbeitszeit-Start aus, optional oder verpflichtend ist.', max_length=20, verbose_name='GPS-Erfassung'),
        ),
        migrations.AddField(
            model_name='company',
            name='gps_visible_to_admin',
            field=models.BooleanField(default=True, verbose_name='GPS für Admin sichtbar'),
        ),
        migrations.AddField(
            model_name='company',
            name='gps_visible_to_employee',
            field=models.BooleanField(default=True, verbose_name='GPS für Mitarbeiter sichtbar'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['gps_capture_mode'], name='companies_c_gps_cap_35f1c7_idx'),
        ),
    ]
