# Generated by Django 5.2.12 on 2026-04-06 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companymembership_can_manage_projects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gps_tracking_mode',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('optional', 'Optional'), ('required', 'Required')], default='disabled', max_length=20, verbose_name='GPS Tracking Modus'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['gps_tracking_mode'], name='companies_c_gps_tra_27d576_idx'),
        ),
    ]
