# Generated by Django 5.2.12 on 2026-03-14 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companymembership_can_manage_projects_and_more'),
        ('projects', '0002_alter_project_created_by_alter_project_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimePublicIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.PositiveBigIntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worktime_public_id_sequence', to='companies.company')),
            ],
            options={
                'verbose_name': 'Work time public ID sequence',
                'verbose_name_plural': 'Work time public ID sequences',
            },
        ),
        migrations.CreateModel(
            name='WorkTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('entry_type', models.CharField(choices=[('timer', 'Timer'), ('manual', 'Manual')], default='timer', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='running', max_length=20)),
                ('work_date', models.DateField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_worktime_entries', to='companies.companymembership')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktime_entries', to='companies.company')),
                ('employee_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worktime_entries', to='companies.companymembership')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worktime_entries', to='projects.project')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_worktime_entries', to='companies.companymembership')),
            ],
            options={
                'verbose_name': 'Work time entry',
                'verbose_name_plural': 'Work time entries',
                'ordering': ('-work_date', '-started_at', '-created_at'),
                'indexes': [models.Index(fields=['company', 'work_date'], name='worktime_wo_company_9f9257_idx'), models.Index(fields=['employee_membership', 'work_date'], name='worktime_wo_employe_2ae851_idx'), models.Index(fields=['status'], name='worktime_wo_status_8cac52_idx'), models.Index(fields=['project'], name='worktime_wo_project_28b470_idx'), models.Index(fields=['started_at'], name='worktime_wo_started_2c7508_idx')],
            },
        ),
    ]
