# Generated by Django 5.2.12 on 2026-04-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_gps_capture_mode_and_more'),
        ('projects', '0002_alter_project_created_by_alter_project_updated_by'),
        ('worktime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimeentry',
            name='check_in_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='worktimeentry',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='worktimeentry',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='worktimeentry',
            name='check_in_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='worktimeentry',
            index=models.Index(fields=['check_in_recorded_at'], name='worktime_wo_check_i_fda68d_idx'),
        ),
    ]
