# Generated by Django 5.2.12 on 2026-03-14 20:13

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companymembership_can_manage_projects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPublicIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('employee_membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_public_id_sequence', to='companies.companymembership')),
            ],
            options={
                'verbose_name': 'Document Public ID Sequence',
                'verbose_name_plural': 'Document Public ID Sequences',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('contract', 'Contract'), ('sick_note', 'Sick Note'), ('vacation_attachment', 'Vacation Attachment'), ('other', 'Other')], db_index=True, default='general', max_length=30)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('company_admin', 'Company Admin'), ('company_all', 'Company All')], db_index=True, default='company_admin', max_length=20)),
                ('file', models.FileField(upload_to=apps.documents.models.document_file_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company')),
                ('employee_membership', models.ForeignKey(blank=True, help_text='Optional employee relation for employee-specific documents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='companies.companymembership')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['company', 'category'], name='documents_d_company_501eb2_idx'), models.Index(fields=['company', 'employee_membership'], name='documents_d_company_b2991e_idx'), models.Index(fields=['company', 'visibility'], name='documents_d_company_83f77b_idx'), models.Index(fields=['company', 'is_active'], name='documents_d_company_594080_idx')],
            },
        ),
    ]
