# Generated by Django 5.2.12 on 2026-03-12 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPublicIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='customer', max_length=50, unique=True)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Public ID Sequence',
                'verbose_name_plural': 'Customer Public ID Sequences',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('customer_number', models.CharField(blank=True, max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('house_number', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, default='Deutschland', max_length=120)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('vat_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers_customer',
                'ordering': ['name', '-created_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='customers_c_company_ecdc25_idx'), models.Index(fields=['company', 'name'], name='customers_c_company_10527e_idx'), models.Index(fields=['public_id'], name='customers_c_public__441f8b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('customer_number', ''), _negated=True), fields=('company', 'customer_number'), name='unique_customer_number_per_company'), models.UniqueConstraint(fields=('company', 'name'), name='unique_customer_name_per_company')],
            },
        ),
    ]
