# Generated by Django 5.2.12 on 2026-03-12 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['company__company_name', 'name', '-created_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customerpublicidsequence',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'customer_number'], name='customers_c_company_fa3ab1_idx'),
        ),
        migrations.AlterModelTable(
            name='customerpublicidsequence',
            table='customers_public_id_sequence',
        ),
    ]
