# Generated by Django 5.2.12 on 2026-03-13 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('customers', '0004_alter_customer_customer_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_number_per_company',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_c_company_fa3ab1_idx',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_number'], name='customers_c_custome_3dcafd_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_number', ''), _negated=True), fields=('company', 'customer_number'), name='unique_customer_number_global'),
        ),
    ]
